import {
  Archive,
  BadgeCheck,
  Box,
  Brush,
  Camera,
  Check,
  ChevronRight,
  Crop,
  Download,
  Edit3,
  Image,
  Images,
  Layers3,
  LayoutDashboard,
  LayoutGrid,
  Package,
  Palette,
  PanelsTopLeft,
  PersonStanding,
  Rows3,
  Search,
  Settings,
  Shirt,
  SlidersHorizontal,
  Sparkles,
  Tags,
  Upload,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";
import type { PdpStudioIconName } from "../types";

const ICONS: Record<PdpStudioIconName, LucideIcon> = {
  archive: Archive,
  badge: BadgeCheck,
  batch: Rows3,
  brand: Tags,
  brush: Brush,
  camera: Camera,
  check: Check,
  chevron: ChevronRight,
  crop: Crop,
  download: Download,
  edit: Edit3,
  export: Download,
  gallery: Images,
  grid: LayoutGrid,
  home: LayoutDashboard,
  image: Image,
  layers: Layers3,
  layout: PanelsTopLeft,
  magic: WandSparkles,
  model: Shirt,
  palette: Palette,
  pose: PersonStanding,
  product: Package,
  resize: Crop,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  template: Box,
  upload: Upload,
  wand: SlidersHorizontal,
};

export function PdpStudioIcon({ name, className }: { name: PdpStudioIconName; className?: string }) {
  const Icon = ICONS[name];
  return <Icon className={className} aria-hidden />;
}
