import type { PdpStudioDashboardView } from "../types";
import { mapClothingPhotoShootView } from "../clothing-photoshoot/mappers/clothingPhotoShootMapper";

export function mapPdpStudioDashboardView(): PdpStudioDashboardView {
  return {
    sidebarGroups: [
      {
        items: [
          { id: "home", label: "Home", icon: "home", active: true },
          { id: "create", label: "Create", icon: "magic" },
          { id: "photoshoot", label: "Photoshoot", icon: "camera", href: "/pdp-studio/clothing-photoshoot" },
          { id: "pdp-sets", label: "PDP Sets", icon: "gallery" },
          { id: "ai-tools", label: "AI Tools", icon: "sparkles" },
          { id: "batch", label: "Batch", icon: "batch" },
        ],
      },
      {
        label: "Content",
        items: [
          { id: "products", label: "Products", icon: "product" },
          { id: "designs", label: "Designs", icon: "layout" },
          { id: "brand-kit", label: "Brand Kit", icon: "brand" },
          { id: "templates", label: "Templates", icon: "template" },
        ],
      },
      {
        label: "Account",
        items: [{ id: "preferences", label: "Preferences", icon: "settings" }],
      },
    ],
    tools: [
      {
        id: "clothing-photoshoot",
        label: "Clothing photoshoot",
        description: "Upload a clothing image, select model, background, and pose, then preview the photoshoot setup.",
        category: "Create",
        icon: "camera",
        status: "build-now",
        href: "/pdp-studio/clothing-photoshoot",
      },
      {
        id: "start-photo",
        label: "Start from product photo",
        description: "Upload one product image and choose the PDP output goal.",
        category: "Create",
        icon: "upload",
        status: "build-now",
        active: true,
      },
      {
        id: "pdp-hero",
        label: "PDP Hero",
        description: "Generate the main product detail image for Shopify.",
        category: "PDP Sets",
        icon: "image",
        status: "build-now",
      },
      {
        id: "pdp-gallery",
        label: "PDP Gallery Set",
        description: "Create hero, close-up, lifestyle, detail, and social variants.",
        category: "PDP Sets",
        icon: "gallery",
        status: "build-now",
      },
      {
        id: "product-staging",
        label: "Product Staging",
        description: "Place the product into a controlled lifestyle scene.",
        category: "AI Tools",
        icon: "sparkles",
        status: "build-now",
      },
      {
        id: "virtual-model",
        label: "Virtual Model",
        description: "Preview apparel and wearable products on a selected model.",
        category: "AI Tools",
        icon: "model",
        status: "build-now",
      },
      {
        id: "ghost-mannequin",
        label: "Ghost Mannequin",
        description: "Create clean apparel PDP images without a visible model.",
        category: "AI Tools",
        icon: "layers",
        status: "build-now",
      },
      {
        id: "flat-lay",
        label: "Flat Lay",
        description: "Build top-down apparel and accessory layouts.",
        category: "AI Tools",
        icon: "grid",
        status: "build-now",
      },
      {
        id: "studio-shot",
        label: "Studio Shot",
        description: "Generate simple ecommerce product shots with studio backgrounds.",
        category: "AI Tools",
        icon: "camera",
        status: "build-now",
      },
      {
        id: "product-beautifier",
        label: "Product Beautifier",
        description: "Improve product presentation while keeping the item recognizable.",
        category: "AI Tools",
        icon: "wand",
        status: "build-now",
      },
      {
        id: "edit-ai",
        label: "Edit with AI",
        description: "Apply a typed edit instruction to an uploaded product image.",
        category: "AI Tools",
        icon: "edit",
        status: "build-now",
      },
      {
        id: "ai-backgrounds",
        label: "AI Backgrounds",
        description: "Swap clean, lifestyle, or prompt-based PDP backgrounds.",
        category: "AI Tools",
        icon: "palette",
        status: "build-now",
      },
      {
        id: "background-remover",
        label: "Background Remover",
        description: "Prepare transparent or white-background product images.",
        category: "AI Tools",
        icon: "brush",
        status: "next",
      },
      {
        id: "resize-export",
        label: "Resize / Export",
        description: "Prepare Shopify and marketplace-ready aspect ratios.",
        category: "Export",
        icon: "resize",
        status: "build-now",
      },
      {
        id: "batch-generate",
        label: "Batch Generate",
        description: "Apply one PDP preset to many product images.",
        category: "Batch",
        icon: "batch",
        status: "next",
      },
    ],
    workflow: [
      { id: "upload", title: "Upload product image", description: "Start with product, catalog, or Shopify media.", icon: "upload" },
      { id: "goal", title: "Pick output goal", description: "Hero, gallery set, staging, model, or export.", icon: "badge" },
      { id: "background", title: "Choose background", description: "Studio, transparent, original, lifestyle, or prompt.", icon: "palette" },
      { id: "model", title: "Choose model", description: "No model, mannequin, preset model, or uploaded model.", icon: "model" },
      { id: "pose", title: "Choose pose", description: "Front, angled, walking, sitting, detail, or random.", icon: "pose" },
      { id: "prompt", title: "Add prompt", description: "Optional creative instruction on top of locked PDP rules.", icon: "edit" },
      { id: "generate", title: "Generate variants", description: "Create one or more PDP-ready image options.", icon: "sparkles" },
      { id: "pick", title: "Pick images for PDP", description: "Select the final hero and gallery variants.", icon: "check" },
      { id: "export", title: "Export Shopify sizes", description: "Download or prepare product-page image sizes.", icon: "download" },
    ],
    backgrounds: [
      { id: "white", label: "White", description: "Classic clean PDP base.", icon: "palette", swatch: "#ffffff" },
      { id: "grey", label: "Grey", description: "Soft neutral ecommerce base.", icon: "palette", swatch: "#e7e7e7" },
      { id: "beige", label: "Beige", description: "Warm studio background.", icon: "palette", swatch: "#e8dfd0" },
      { id: "pastel", label: "Pastel colors", description: "Soft color set for brand-friendly variants.", icon: "palette", swatch: "#dce9ff" },
      { id: "transparent", label: "Transparent", description: "PNG cutout export preview.", icon: "crop", swatch: "checker" },
      { id: "original", label: "Original image", description: "Keep the uploaded product background.", icon: "image" },
      { id: "lifestyle", label: "Lifestyle scene", description: "Context scene for product staging.", icon: "sparkles", swatch: "#d7ece4" },
      { id: "prompt", label: "Prompt-based", description: "Describe a custom PDP background.", icon: "edit", swatch: "#e8e5ff" },
    ],
    models: [
      { id: "none", label: "No model", description: "Use for studio, cutout, and packaging shots.", icon: "product" },
      { id: "default", label: "Default model", description: "Fast on-body apparel preview.", icon: "model" },
      { id: "female", label: "Female model", description: "Preset model direction for apparel PDPs.", icon: "model" },
      { id: "male", label: "Male model", description: "Preset model direction for apparel PDPs.", icon: "model" },
      { id: "mannequin", label: "Mannequin", description: "Structured ghost or visible mannequin output.", icon: "layers" },
      { id: "uploaded", label: "Uploaded model image", description: "Use a merchant-provided model reference.", icon: "upload" },
    ],
    poses: [
      { id: "front", label: "Front", description: "Clean primary PDP pose.", icon: "pose" },
      { id: "angled", label: "Angled", description: "Three-quarter product view.", icon: "pose" },
      { id: "walking", label: "Walking", description: "Lifestyle movement shot.", icon: "pose" },
      { id: "sitting", label: "Sitting", description: "Editorial seated option.", icon: "pose" },
      { id: "detail", label: "Hand/detail", description: "Close detail or held-product view.", icon: "search" },
      { id: "random", label: "Random", description: "Fast variation exploration.", icon: "sparkles" },
    ],
    clothingPhotoShoot: mapClothingPhotoShootView(),
    exports: [
      { id: "shopify-hero", label: "Shopify PDP hero", size: "2048 x 2048", description: "Primary product page image.", icon: "export" },
      { id: "shopify-gallery", label: "Shopify gallery square", size: "1600 x 1600", description: "Gallery image set.", icon: "gallery" },
      { id: "collection-card", label: "Shopify collection card", size: "1200 x 1500", description: "Collection grid preview.", icon: "layout" },
      { id: "social-story", label: "Social story", size: "1080 x 1920", description: "Story and short-form preview.", icon: "image" },
      { id: "marketplace-square", label: "Marketplace square", size: "2000 x 2000", description: "General marketplace export.", icon: "archive" },
      { id: "transparent-png", label: "Transparent PNG", size: "2048 x 2048", description: "Cutout-ready asset.", icon: "crop" },
    ],
    roadmap: [
      { id: "ui", label: "Dashboard UI", description: "Rich UI shell, navigation, and static controls.", status: "build-now" },
      { id: "test-lab", label: "Test lab reuse", description: "Move existing inputs into reusable PDP editor components.", status: "next" },
      { id: "queue", label: "Batch queue", description: "Add durable backend jobs and status polling.", status: "later" },
    ],
  };
}
