"use client";
import{useEffect,useState}from"react";import{getPdpStudioProfile,updatePdpStudioProfile}from"../../platform/services/pdpStudioProfileService";import{getPdpBilling,getPdpUsage,getWorkspaceSettings,inviteWorkspaceMember,listWorkspaceMembers,listWorkspaces,updateWorkspaceSettings,type UsageDto,type WorkspaceDto,type WorkspaceSettings}from"../../platform/services/pdpStudioWorkspaceService";
export interface PreferenceToggleState{contentSafety:boolean}
const DEFAULT:WorkspaceSettings={language:"English",appearance:"system",exportFormat:"png",exportQuality:94,contentSafety:true,defaultWidth:1200,defaultHeight:1200,description:""};
export function usePreferencesWorkspaceUi(){const[activeSection,setActiveSection]=useState("account-profile"),[displayName,setDisplayName]=useState(""),[email,setEmail]=useState(""),[language,setLanguage]=useState("English"),[appearance,setAppearance]=useState("system"),[spaceName,setSpaceName]=useState(""),[spaceDescription,setSpaceDescription]=useState(""),[exportFormat,setExportFormat]=useState("png"),[exportQuality,setExportQuality]=useState(94),[savedSection,setSavedSection]=useState(""),[toggles,setToggles]=useState<PreferenceToggleState>({contentSafety:true}),[workspaces,setWorkspaces]=useState<WorkspaceDto[]>([]),[members,setMembers]=useState<Array<{accountId:string;name:string;email:string;role:string;joinedAt:string}>>([]),[usage,setUsage]=useState<UsageDto|null>(null),[billing,setBilling]=useState<Awaited<ReturnType<typeof getPdpBilling>>|null>(null),[error,setError]=useState("");
 useEffect(()=>{void Promise.all([getPdpStudioProfile(),getWorkspaceSettings(),listWorkspaces(),getPdpUsage(),getPdpBilling()]).then(async([profile,settings,spaces,usageValue,billingValue])=>{setDisplayName(profile.name);setEmail(profile.email);setSpaceName(profile.workspace.name);setLanguage(settings.language);setAppearance(settings.appearance);setExportFormat(settings.exportFormat);setExportQuality(settings.exportQuality);setSpaceDescription(settings.description);setToggles({contentSafety:settings.contentSafety});setWorkspaces(spaces);setUsage(usageValue);setBilling(billingValue);const active=spaces.find(space=>space.id===profile.workspace.id)??spaces[0];if(active&&["owner","admin"].includes(active.role))setMembers(await listWorkspaceMembers(active.id))}).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load settings."))},[]);
 function toggle(key:keyof PreferenceToggleState){setToggles(current=>({...current,[key]:!current[key]}));setSavedSection("")}
 async function save(section:string){setError("");try{if(section==="account-profile"||section==="space-details")await updatePdpStudioProfile({name:displayName,workspaceName:spaceName});if(section==="space-settings"||section==="space-details"||section==="account-profile")await updateWorkspaceSettings({language,appearance:appearance as "light"|"system",exportFormat:exportFormat as "png"|"jpeg"|"webp",exportQuality,contentSafety:toggles.contentSafety,defaultWidth:1200,defaultHeight:1200,description:spaceDescription});setSavedSection(section)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save settings.")}}
 async function invite(emailValue:string,role:string){const active=workspaces[0];if(!active)return;const invitation=await inviteWorkspaceMember(active.id,emailValue,role);setMembers(await listWorkspaceMembers(active.id));return invitation}
 return{activeSection,displayName,email,language,appearance,spaceName,spaceDescription,exportFormat,exportQuality,savedSection,toggles,workspaces,members,usage,billing,error,setActiveSection,setDisplayName,setLanguage,setAppearance,setSpaceName,setSpaceDescription,setExportFormat,setExportQuality,toggle,save,invite};}
