import { pdpStudioApiRequest, pdpStudioPlatformUrl } from "../../platform/services/pdpStudioApiClient";
import type { DesignAnnotation, DesignApproval, DesignDocument, DesignRevision, PdpDesign, PdpTemplate } from "../types/pdpStudioDesign";
export async function listDesigns() { return pdpStudioApiRequest<{ ok: true; designs: PdpDesign[]; hasMore: boolean; nextBefore: string | null }>("/designs"); }
export async function getDesign(id: string) { return (await pdpStudioApiRequest<{ ok: true; design: PdpDesign }>(`/designs/${encodeURIComponent(id)}`)).design; }
export async function createDesign(input: { name: string; document?: DesignDocument; sourceAssetId?: string; width?: number; height?: number }) { return (await pdpStudioApiRequest<{ ok: true; design: PdpDesign }>("/designs", { method: "POST", body: JSON.stringify(input) })).design; }
export async function saveDesign(id: string, input: { expectedRevision: number; name?: string; checkpointName?: string; document: DesignDocument }) { return (await pdpStudioApiRequest<{ ok: true; design: PdpDesign }>(`/designs/${encodeURIComponent(id)}`, { method: "PUT", body: JSON.stringify(input) })).design; }
export async function deleteDesign(id: string) { await pdpStudioApiRequest<unknown>(`/designs/${encodeURIComponent(id)}`, { method: "DELETE" }); }
export async function listRevisions(id: string) { return (await pdpStudioApiRequest<{ ok: true; revisions: DesignRevision[] }>(`/designs/${encodeURIComponent(id)}/revisions`)).revisions; }
export async function restoreRevision(id: string, revision: number) { return (await pdpStudioApiRequest<{ ok: true; design: PdpDesign }>(`/designs/${encodeURIComponent(id)}/revisions/${revision}/restore`, { method: "POST" })).design; }
export const renderDesignUrl = (id: string, format: "png" | "jpeg" | "webp" = "png") => pdpStudioPlatformUrl(`/designs/${encodeURIComponent(id)}/render?format=${format}`);
export async function listAnnotations(id: string) { return (await pdpStudioApiRequest<{ ok: true; annotations: DesignAnnotation[] }>(`/designs/${encodeURIComponent(id)}/annotations`)).annotations; }
export async function createAnnotation(id: string, input: { x: number; y: number; body: string }) { return (await pdpStudioApiRequest<{ ok: true; annotation: DesignAnnotation }>(`/designs/${encodeURIComponent(id)}/annotations`, { method: "POST", body: JSON.stringify(input) })).annotation; }
export async function replyAnnotation(id: string, annotationId: string, body: string) { return (await pdpStudioApiRequest<{ ok: true; annotation: DesignAnnotation }>(`/designs/${encodeURIComponent(id)}/annotations/${annotationId}/replies`, { method: "POST", body: JSON.stringify({ body }) })).annotation; }
export async function resolveAnnotation(id: string, annotationId: string, resolved: boolean) { return (await pdpStudioApiRequest<{ ok: true; annotation: DesignAnnotation }>(`/designs/${encodeURIComponent(id)}/annotations/${annotationId}`, { method: "PATCH", body: JSON.stringify({ resolved }) })).annotation; }
export async function getApproval(id: string) { return (await pdpStudioApiRequest<{ ok: true; approval: DesignApproval }>(`/designs/${encodeURIComponent(id)}/approval`)).approval; }
export async function setApproval(id: string, input: Pick<DesignApproval, "status" | "note">) { return (await pdpStudioApiRequest<{ ok: true; approval: DesignApproval }>(`/designs/${encodeURIComponent(id)}/approval`, { method: "PUT", body: JSON.stringify(input) })).approval; }
export async function listTemplates() { return (await pdpStudioApiRequest<{ ok: true; templates: PdpTemplate[] }>("/templates")).templates; }
export async function createTemplate(input: { name: string; description?: string; designId?: string; document?: DesignDocument }) { return (await pdpStudioApiRequest<{ ok: true; template: PdpTemplate }>("/templates", { method: "POST", body: JSON.stringify(input) })).template; }
export async function deleteTemplate(id: string) { await pdpStudioApiRequest<unknown>(`/templates/${encodeURIComponent(id)}`, { method: "DELETE" }); }
export async function createFromTemplate(id: string, name?: string) { return (await pdpStudioApiRequest<{ ok: true; design: PdpDesign }>(`/templates/${encodeURIComponent(id)}/designs`, { method: "POST", body: JSON.stringify({ name }) })).design; }
