export type DesignLayerType = "image" | "text" | "shape" | "drawing";
export interface DesignEffects { brightness: number; contrast: number; saturation: number; temperature: number; tint: number; blur: number; shadow: { enabled: boolean; color: string; blur: number; offsetX: number; offsetY: number; opacity: number }; outline: { enabled: boolean; color: string; width: number }; reflection: { enabled: boolean; opacity: number; gap: number }; filter: "none" | "grayscale" | "sepia" | "warm" | "cool"; texture: "none" | "grain" | "paper"; }
export interface DesignLayer { id: string; type: DesignLayerType; name: string; x: number; y: number; width: number; height: number; rotation: number; opacity: number; visible: boolean; locked: boolean; blendMode: string; assetId?: string | undefined; assetUrl?: string | undefined; text?: string | undefined; fontFamily?: string | undefined; fontSize?: number | undefined; fontWeight?: number | undefined; color?: string | undefined; shape?: "rectangle" | "ellipse" | "line" | "arrow" | undefined; fill?: string | undefined; stroke?: string | undefined; strokeWidth?: number | undefined; points?: number[] | undefined; crop?: { x: number; y: number; width: number; height: number } | undefined; effects: DesignEffects; }
export interface DesignDocument { version: 1; canvas: { width: number; height: number; background: string }; layers: DesignLayer[]; }
export interface PdpDesign { id: string; workspaceId: string; name: string; document: DesignDocument; revision: number; thumbnailAssetId: string | null; createdAt: string; updatedAt: string; }
export interface DesignRevision { revision: number; name: string; createdByAccountId: string; createdAt: string; }
export interface DesignAnnotation { id: string; designId: string; createdByAccountId: string; x: number; y: number; body: string; resolved: boolean; resolvedAt: string | null; replies: Array<{ id: string; accountId: string; body: string; createdAt: string }>; createdAt: string; updatedAt: string; }
export interface DesignApproval { status: "pending" | "approved" | "changes_requested"; revision: number; note: string; decidedByAccountId?: string | null; decidedAt: string | null; }
export interface PdpTemplate { id: string; name: string; description: string; document: DesignDocument; createdAt: string; updatedAt: string; }
export const defaultEffects = (): DesignEffects => ({ brightness: 0, contrast: 0, saturation: 0, temperature: 0, tint: 0, blur: 0, shadow: { enabled: false, color: "#000000", blur: 16, offsetX: 0, offsetY: 12, opacity: .25 }, outline: { enabled: false, color: "#ffffff", width: 4 }, reflection: { enabled: false, opacity: .25, gap: 8 }, filter: "none", texture: "none" });
export const emptyDesignDocument = (width = 1200, height = 1200): DesignDocument => ({ version: 1, canvas: { width, height, background: "#ffffff" }, layers: [] });
