"use client";
import { Copy, Eye, EyeOff, Lock, Trash2, Unlock } from "lucide-react";
import type { DesignDocument, DesignLayer } from "../types/pdpStudioDesign";
interface Props { document:DesignDocument; layer: DesignLayer | null; onDocumentChange(document:DesignDocument):void; onChange(patch: Partial<DesignLayer>):void; onDelete():void; onDuplicate():void; onMove(direction:-1|1):void; }
export function PdpStudioEditorInspector({document,layer,onDocumentChange,onChange,onDelete,onDuplicate,onMove}:Props){ if(!layer) return <aside className="rounded-[16px] border border-[#dfe3ea] bg-white p-5"><h2 className="text-sm font-semibold text-[#111827]">Canvas</h2><p className="mt-2 text-xs leading-5 text-[#64748b]">Resize the output and select its background. Existing layers keep their position.</p><div className="mt-4 grid grid-cols-2 gap-2"><NumberField label="Width" value={document.canvas.width} min={64} max={8192} onChange={width=>onDocumentChange({...document,canvas:{...document.canvas,width}})}/><NumberField label="Height" value={document.canvas.height} min={64} max={8192} onChange={height=>onDocumentChange({...document,canvas:{...document.canvas,height}})}/></div><div className="mt-3"><ColorField label="Background" value={document.canvas.background} onChange={background=>onDocumentChange({...document,canvas:{...document.canvas,background}})}/></div><button className="editor-tool mt-4 w-full justify-center border border-[#dfe3ea]" onClick={()=>onDocumentChange({...document,canvas:{...document.canvas,width:document.canvas.height,height:document.canvas.width}})}>Swap orientation</button></aside>;
 const effects=layer.effects; return <aside className="max-h-[calc(100vh-12rem)] overflow-y-auto rounded-[16px] border border-[#dfe3ea] bg-white p-4 shadow-sm">
  <div className="flex items-center justify-between"><div><p className="text-[11px] uppercase tracking-[.14em] text-[#94a3b8]">Selected layer</p><h2 className="mt-1 truncate text-sm font-semibold text-[#111827]">{layer.name}</h2></div><div className="flex"><Icon onClick={()=>onChange({visible:!layer.visible})}>{layer.visible?<Eye size={16}/>:<EyeOff size={16}/>}</Icon><Icon onClick={()=>onChange({locked:!layer.locked})}>{layer.locked?<Lock size={16}/>:<Unlock size={16}/>}</Icon></div></div>
  <Section title="Position & transform"><div className="grid grid-cols-2 gap-2"><NumberField label="X" value={layer.x} onChange={x=>onChange({x})}/><NumberField label="Y" value={layer.y} onChange={y=>onChange({y})}/><NumberField label="Width" value={layer.width} min={20} onChange={width=>onChange({width})}/><NumberField label="Height" value={layer.height} min={20} onChange={height=>onChange({height})}/><NumberField label="Rotation" value={layer.rotation} onChange={rotation=>onChange({rotation})}/><NumberField label="Opacity %" value={Math.round(layer.opacity*100)} min={0} max={100} onChange={opacity=>onChange({opacity:opacity/100})}/></div></Section>
  {layer.type==="text"?<Section title="Text"><textarea value={layer.text} onChange={e=>onChange({text:e.target.value})} className="min-h-20 w-full rounded-xl border border-[#dfe3ea] p-3 text-sm outline-none focus:border-[#315EF5]"/><div className="mt-2 grid grid-cols-2 gap-2"><NumberField label="Size" value={layer.fontSize??48} onChange={fontSize=>onChange({fontSize})}/><ColorField label="Color" value={layer.color??"#111827"} onChange={color=>onChange({color})}/></div></Section>:null}
  {layer.type==="shape"?<Section title="Shape"><div className="grid grid-cols-2 gap-2"><ColorField label="Fill" value={layer.fill??"#EEF3FF"} onChange={fill=>onChange({fill})}/><ColorField label="Stroke" value={layer.stroke??"#315EF5"} onChange={stroke=>onChange({stroke})}/></div></Section>:null}
  {layer.type==="image"?<Section title="Crop"><div className="grid grid-cols-2 gap-2"><NumberField label="Crop X %" value={Math.round((layer.crop?.x??0)*100)} min={0} max={95} onChange={value=>onChange({crop:{x:value/100,y:layer.crop?.y??0,width:layer.crop?.width??1,height:layer.crop?.height??1}})}/><NumberField label="Crop Y %" value={Math.round((layer.crop?.y??0)*100)} min={0} max={95} onChange={value=>onChange({crop:{x:layer.crop?.x??0,y:value/100,width:layer.crop?.width??1,height:layer.crop?.height??1}})}/><NumberField label="Crop width %" value={Math.round((layer.crop?.width??1)*100)} min={5} max={100} onChange={value=>onChange({crop:{x:layer.crop?.x??0,y:layer.crop?.y??0,width:value/100,height:layer.crop?.height??1}})}/><NumberField label="Crop height %" value={Math.round((layer.crop?.height??1)*100)} min={5} max={100} onChange={value=>onChange({crop:{x:layer.crop?.x??0,y:layer.crop?.y??0,width:layer.crop?.width??1,height:value/100}})}/></div><button className="mt-2 text-xs font-medium text-[#315EF5]" onClick={()=>onChange({crop:undefined})}>Reset crop</button></Section>:null}
  <Section title="Adjustments"><Range label="Brightness" value={effects.brightness} min={-1} max={1} step={.05} onChange={brightness=>onChange({effects:{...effects,brightness}})}/><Range label="Contrast" value={effects.contrast} min={-1} max={1} step={.05} onChange={contrast=>onChange({effects:{...effects,contrast}})}/><Range label="Saturation" value={effects.saturation} min={-1} max={2} step={.05} onChange={saturation=>onChange({effects:{...effects,saturation}})}/><Range label="Temperature" value={effects.temperature} min={-1} max={1} step={.05} onChange={temperature=>onChange({effects:{...effects,temperature}})}/><Range label="Tint" value={effects.tint} min={-1} max={1} step={.05} onChange={tint=>onChange({effects:{...effects,tint}})}/><Range label="Blur" value={effects.blur} min={0} max={100} step={1} onChange={blur=>onChange({effects:{...effects,blur}})}/></Section>
  <Section title="Effects"><Toggle label="Shadow" checked={effects.shadow.enabled} onChange={enabled=>onChange({effects:{...effects,shadow:{...effects.shadow,enabled}}})}/><Toggle label="Outline" checked={effects.outline.enabled} onChange={enabled=>onChange({effects:{...effects,outline:{...effects.outline,enabled}}})}/><Toggle label="Reflection" checked={effects.reflection.enabled} onChange={enabled=>onChange({effects:{...effects,reflection:{...effects.reflection,enabled}}})}/><label className="mt-3 block text-xs text-[#64748b]">Filter<select value={effects.filter} onChange={e=>onChange({effects:{...effects,filter:e.target.value as typeof effects.filter}})} className="mt-1 h-10 w-full rounded-xl border border-[#dfe3ea] bg-white px-3 text-sm"><option value="none">None</option><option value="grayscale">Black & white</option><option value="sepia">Sepia</option><option value="warm">Warm</option><option value="cool">Cool</option></select></label></Section>
  <Section title="Layer"><div className="grid grid-cols-2 gap-2"><button className="editor-tool justify-center border border-[#dfe3ea]" onClick={()=>onMove(1)}>Bring forward</button><button className="editor-tool justify-center border border-[#dfe3ea]" onClick={()=>onMove(-1)}>Send backward</button><button className="editor-tool justify-center border border-[#dfe3ea]" onClick={onDuplicate}><Copy size={15}/>Duplicate</button><button className="editor-tool justify-center border border-red-200 text-red-600" onClick={onDelete}><Trash2 size={15}/>Delete</button></div></Section>
 </aside>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-5 border-t border-[#edf0f4] pt-4"><h3 className="mb-3 text-xs font-semibold text-[#334155]">{title}</h3>{children}</section>}
function NumberField({label,value,onChange,min,max}:{label:string;value:number;onChange(v:number):void;min?:number;max?:number}){return <label className="text-[11px] text-[#64748b]">{label}<input type="number" value={Math.round(value*100)/100} min={min} max={max} onChange={e=>onChange(Number(e.target.value))} className="mt-1 h-9 w-full rounded-lg border border-[#dfe3ea] px-2 text-sm"/></label>}
function ColorField({label,value,onChange}:{label:string;value:string;onChange(v:string):void}){return <label className="text-[11px] text-[#64748b]">{label}<span className="mt-1 flex h-9 items-center gap-2 rounded-lg border border-[#dfe3ea] px-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="size-5 border-0 bg-transparent"/><span className="text-xs">{value}</span></span></label>}
function Range({label,value,onChange,min,max,step}:{label:string;value:number;onChange(v:number):void;min:number;max:number;step:number}){return <label className="mb-3 block text-[11px] text-[#64748b]"><span className="flex justify-between"><span>{label}</span><span>{Math.round(value*100)/100}</span></span><input type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))} className="mt-1 w-full accent-[#315EF5]"/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange(v:boolean):void}){return <label className="mb-2 flex items-center justify-between text-xs text-[#475569]"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="size-4 accent-[#315EF5]"/></label>}
function Icon({children,onClick}:{children:React.ReactNode;onClick():void}){return <button className="editor-icon" onClick={onClick}>{children}</button>}
