"use client";
import { useState } from "react";
import { PdpStudioDesignCanvas } from "./PdpStudioDesignCanvas";
import { PdpStudioEditorInspector } from "./PdpStudioEditorInspector";
import { PdpStudioEditorToolbar } from "./PdpStudioEditorToolbar";
import { PdpStudioReviewPanel } from "./PdpStudioReviewPanel";
import { usePdpStudioEditor } from "../hooks/usePdpStudioEditor";
export function PdpStudioEditorWorkspace({designId}:{designId:string}){const ui=usePdpStudioEditor(designId); const [commentDraft,setCommentDraft]=useState<{x:number;y:number}|null>(null); const [comment,setComment]=useState("");
 if(ui.status==="loading"||!ui.document) return <div className="grid min-h-[34rem] place-items-center rounded-[18px] bg-white text-sm text-[#64748b]">Loading editor…</div>;
 return <div className="grid gap-3 pb-6"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-[#F06A3C]">Unified product editor</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.02em] text-[#111827]">{ui.design?.name}</h1></div>{ui.error?<p className="max-w-md rounded-xl bg-red-50 px-3 py-2 text-xs text-red-700">{ui.error}</p>:null}</div>
 <PdpStudioEditorToolbar status={ui.status} tool={ui.tool} canUndo={ui.canUndo} canRedo={ui.canRedo} downloadUrl={ui.downloadUrl} onTool={ui.setTool} onText={ui.addText} onShape={ui.addShape} onInsert={ui.insertImage} onUndo={ui.undo} onRedo={ui.redo} onSave={ui.save}/>
 <div className="grid min-h-0 gap-3 xl:grid-cols-[minmax(0,1fr)_19rem]"><PdpStudioDesignCanvas document={ui.document} selectedId={ui.selectedId} annotations={ui.annotations} commentMode={ui.tool==="comment"} drawMode={ui.tool==="draw"} onSelect={ui.setSelectedId} onChange={ui.updateLayer} onComment={(x,y)=>setCommentDraft({x,y})} onDraw={ui.addDrawing}/><div className="grid content-start gap-3"><PdpStudioEditorInspector document={ui.document} layer={ui.selectedLayer} onDocumentChange={ui.setDocument} onChange={patch=>ui.selectedLayer&&ui.updateLayer(ui.selectedLayer.id,patch)} onDelete={ui.removeSelected} onDuplicate={ui.duplicateSelected} onMove={direction=>ui.selectedLayer&&ui.moveLayer(ui.selectedLayer.id,direction)}/><PdpStudioReviewPanel annotations={ui.annotations} revisions={ui.revisions} approval={ui.approval} onResolve={ui.resolve} onReply={ui.reply} onRestore={ui.restore} onApproval={ui.decide}/></div></div>
 {commentDraft?<div className="fixed inset-0 z-[500] grid place-items-center bg-[#0f172a]/30 p-4" onMouseDown={()=>setCommentDraft(null)}><div className="w-full max-w-sm rounded-[18px] bg-white p-5 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><h2 className="text-base font-semibold">Add pinned comment</h2><textarea autoFocus value={comment} onChange={e=>setComment(e.target.value)} className="mt-3 min-h-28 w-full rounded-xl border border-[#dfe3ea] p-3 text-sm outline-none focus:border-[#315EF5]" placeholder="What should change?"/><div className="mt-3 flex justify-end gap-2"><button className="editor-tool" onClick={()=>setCommentDraft(null)}>Cancel</button><button disabled={!comment.trim()} className="h-10 rounded-xl bg-[#315EF5] px-4 text-sm font-medium text-white disabled:opacity-40" onClick={async()=>{await ui.addAnnotation(commentDraft.x,commentDraft.y,comment);setComment("");setCommentDraft(null);ui.setTool("select")}}>Add comment</button></div></div></div>:null}
 </div>}
