"use client";
import { CheckCircle2, History, MessageCircle, RotateCcw } from "lucide-react";
import { useState } from "react";
import type { DesignAnnotation, DesignApproval, DesignRevision } from "../types/pdpStudioDesign";
interface Props { annotations:DesignAnnotation[]; revisions:DesignRevision[]; approval:DesignApproval|null; onResolve(id:string,resolved:boolean):void; onReply(id:string,body:string):void; onRestore(revision:number):void; onApproval(value:Pick<DesignApproval,"status"|"note">):void; }
export function PdpStudioReviewPanel({annotations,revisions,approval,onResolve,onReply,onRestore,onApproval}:Props){const [tab,setTab]=useState<"comments"|"history">("comments"); const [note,setNote]=useState(approval?.note??""); return <section className="rounded-[16px] border border-[#dfe3ea] bg-white shadow-sm">
 <div className="flex border-b border-[#edf0f4] p-2"><Tab active={tab==="comments"} onClick={()=>setTab("comments")}><MessageCircle size={15}/>Comments <span className="rounded-full bg-[#eef3ff] px-2 py-0.5 text-[10px] text-[#315EF5]">{annotations.filter(a=>!a.resolved).length}</span></Tab><Tab active={tab==="history"} onClick={()=>setTab("history")}><History size={15}/>History</Tab></div>
 {tab==="comments"?<div className="max-h-72 overflow-y-auto p-3">{annotations.length?annotations.map((item,index)=><Comment key={item.id} item={item} index={index} onResolve={onResolve} onReply={onReply}/>):<p className="p-4 text-center text-xs leading-5 text-[#64748b]">Choose Comment in the toolbar, then click the canvas to pin review feedback.</p>}</div>:<div className="max-h-72 overflow-y-auto p-3">{revisions.map(row=><div key={row.revision} className="mb-2 flex items-center gap-3 rounded-xl border border-[#edf0f4] p-3"><span className="grid size-8 place-items-center rounded-full bg-[#f3f4f6] text-xs font-semibold">{row.revision}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-[#111827]">{row.name}</p><p className="text-[10px] text-[#94a3b8]">{new Date(row.createdAt).toLocaleString()}</p></div><button className="editor-icon" aria-label={`Restore revision ${row.revision}`} onClick={()=>onRestore(row.revision)}><RotateCcw size={15}/></button></div>)}</div>}
 <div className="border-t border-[#edf0f4] p-3"><p className="text-xs font-semibold text-[#334155]">Approval</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional review note" className="mt-2 min-h-16 w-full rounded-xl border border-[#dfe3ea] p-2 text-xs outline-none focus:border-[#315EF5]"/><div className="mt-2 grid grid-cols-2 gap-2"><button className="h-9 rounded-xl border border-orange-200 bg-orange-50 text-xs font-medium text-orange-700" onClick={()=>onApproval({status:"changes_requested",note})}>Request changes</button><button className="inline-flex h-9 items-center justify-center gap-1 rounded-xl bg-emerald-600 text-xs font-medium text-white" onClick={()=>onApproval({status:"approved",note})}><CheckCircle2 size={14}/>Approve</button></div>{approval?.status&&approval.status!=="pending"?<p className="mt-2 text-[11px] text-[#64748b]">Current: {approval.status.replace("_"," ")} for revision {approval.revision}</p>:null}</div>
 </section>}
function Comment({item,index,onResolve,onReply}:{item:DesignAnnotation;index:number;onResolve(id:string,resolved:boolean):void;onReply(id:string,body:string):void}){const [body,setBody]=useState("");return <article className={`mb-2 rounded-xl border p-3 ${item.resolved?"border-[#edf0f4] bg-[#f8fafc] opacity-70":"border-orange-100 bg-orange-50/40"}`}><div className="flex gap-2"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-[#F06A3C] text-[10px] font-bold text-white">{index+1}</span><div className="min-w-0 flex-1"><p className="text-xs leading-5 text-[#334155]">{item.body}</p>{item.replies.map(reply=><p key={reply.id} className="mt-2 border-l-2 border-[#dfe3ea] pl-2 text-[11px] text-[#64748b]">{reply.body}</p>)}<div className="mt-2 flex gap-1"><input value={body} onChange={e=>setBody(e.target.value)} placeholder="Reply" className="h-8 min-w-0 flex-1 rounded-lg border border-[#dfe3ea] px-2 text-[11px]"/><button disabled={!body.trim()} onClick={()=>{onReply(item.id,body);setBody("")}} className="rounded-lg bg-white px-2 text-[11px] font-medium text-[#315EF5] disabled:opacity-40">Send</button><button onClick={()=>onResolve(item.id,!item.resolved)} className="rounded-lg px-2 text-[11px] text-[#64748b]">{item.resolved?"Reopen":"Resolve"}</button></div></div></div></article>}
function Tab({active,children,onClick}:{active:boolean;children:React.ReactNode;onClick():void}){return <button onClick={onClick} className={`inline-flex h-9 flex-1 items-center justify-center gap-2 rounded-xl text-xs font-medium ${active?"bg-[#f3f4f6] text-[#111827]":"text-[#64748b]"}`}>{children}</button>}
