"use client";

import Image from "next/image";
import { cn } from "@/app/shared/lib/utils";

/**
 * 3D rotating turntable with 5 model images.
 * The selected model is front-center, bright and largest.
 * Others are positioned behind, darker and smaller — like a lazy-susan.
 */

interface ModelPlatformProps {
  /** Array of 5 outfit/model image URLs */
  images: string[];
  /** Currently selected index (0-4) */
  selectedIndex: number;
  /** Called when a model position is clicked */
  onSelect: (index: number) => void;
}

/**
 * Each position on the turntable has:
 * - translateX: horizontal offset from center (%)
 * - translateZ: depth offset (px, negative = further away)
 * - scale: size multiplier
 * - brightness: CSS brightness filter
 * - zIndex: stacking order
 */
const POSITION_STYLES: {
  translateX: string;
  translateZ: number;
  scale: number;
  brightness: number;
  zIndex: number;
}[] = [
  // Position 0: CENTER (front, selected)
  { translateX: "0%", translateZ: 0, scale: 1, brightness: 1, zIndex: 5 },
  // Position 1: RIGHT
  { translateX: "55%", translateZ: -120, scale: 0.78, brightness: 0.55, zIndex: 3 },
  // Position 2: FAR RIGHT (back)
  { translateX: "85%", translateZ: -220, scale: 0.62, brightness: 0.35, zIndex: 1 },
  // Position 3: FAR LEFT (back)
  { translateX: "-85%", translateZ: -220, scale: 0.62, brightness: 0.35, zIndex: 1 },
  // Position 4: LEFT
  { translateX: "-55%", translateZ: -120, scale: 0.78, brightness: 0.55, zIndex: 3 },
];

function getPositionIndex(
  modelIndex: number,
  selectedIndex: number,
  total: number
): number {
  // Calculate relative position from selected
  const diff = ((modelIndex - selectedIndex) % total + total) % total;
  return diff;
}

/** Platform disc image path — generated by scripts/process-platform-images.ts */
const DISC_IMAGE = "/images/ai-stylist/platform-disc.png";

export function ModelPlatform({
  images,
  selectedIndex,
  onSelect,
}: ModelPlatformProps) {
  const total = images.length;

  return (
    <div className="relative flex h-full w-full flex-col">
      {/* 3D Scene container */}
      <div
        className="relative flex-1"
        style={{ perspective: "1200px" }}
      >
        {/* Models */}
        {images.map((src, i) => {
          const posIdx = getPositionIndex(i, selectedIndex, total);
          const pos = POSITION_STYLES[posIdx];
          const isSelected = posIdx === 0;

          return (
            <button
              key={i}
              type="button"
              className={cn(
                "absolute top-0 left-1/2 h-full transition-all duration-700 ease-in-out",
                isSelected ? "cursor-default" : "cursor-pointer"
              )}
              style={{
                transform: `translateX(calc(-50% + ${pos.translateX})) translateZ(${pos.translateZ}px) scale(${pos.scale})`,
                filter: `brightness(${pos.brightness})`,
                zIndex: pos.zIndex,
                width: "55%",
              }}
              onClick={() => {
                if (!isSelected) onSelect(i);
              }}
              tabIndex={isSelected ? -1 : 0}
            >
              <Image
                src={src}
                alt={`Model outfit ${i + 1}`}
                fill
                className="object-contain object-bottom"
                sizes="310px"
                priority={isSelected}
              />
            </button>
          );
        })}
      </div>

      {/* Platform disc */}
      <div className="relative z-0 -mt-[1.667vw] flex shrink-0 items-center justify-center">
        <div className="w-[85%]">
          <Image
            src={DISC_IMAGE}
            alt="Turntable platform"
            width={1200}
            height={1800}
            className="h-auto w-full"
            priority
          />
        </div>
      </div>
    </div>
  );
}
