import type { CapacityScenarioOption, CapacityTargetOption } from "../types";
import type { TryOnModelId } from "../../lib/models";

export const DEFAULT_CAPACITY_TRY_ON_MODEL: TryOnModelId = "gemini-2.5-flash-image";

export const CAPACITY_TARGETS: CapacityTargetOption[] = [
  {
    id: "local",
    label: "Local backend",
    description: process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000",
    baseUrl: process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000",
    isLive: false,
  },
  {
    id: "test",
    label: "Test backend",
    description: "test-be-9a7k.primestyleai.com",
    baseUrl: "https://test-be-9a7k.primestyleai.com",
    isLive: false,
  },
  {
    id: "live",
    label: "Live API",
    description: "api.primestyleai.com",
    baseUrl: "https://api.primestyleai.com",
    isLive: true,
  },
];

export const CAPACITY_SCENARIOS: CapacityScenarioOption[] = [
  {
    id: "health",
    label: "Backend health check",
    description: "Measures API latency, Mongo readiness, SSE counters, and Node responsiveness without using Gemini.",
    helper: "Safe for thousands of requests. No Gemini quota is consumed.",
    method: "GET",
    path: "target-specific health route",
    isGeminiSafe: true,
    maxTotalRequests: 10000,
    maxVirtualUsers: 1000,
    estimatedTryOnCallsPerRequest: 0,
    estimatedSizingCallsPerRequest: 0,
  },
  {
    id: "ai-sizing-real",
    label: "Real SDK sizing result",
    description: "Runs the SDK photo path: compressed age-check thumbnail and photo size recommendation.",
    helper: "Consumes real Gemini sizing/vision quota, but no image try-on quota.",
    method: "POST",
    path: "/api/v1/sizing/age-check -> /api/v1/sizing/recommend",
    isGeminiSafe: false,
    maxTotalRequests: 110,
    maxVirtualUsers: 110,
    estimatedTryOnCallsPerRequest: 0,
    estimatedSizingCallsPerRequest: 2,
  },
  {
    id: "tryon-submit-only-real",
    label: "Try-on submit only",
    description: "Submits real SDK try-on jobs and stops after the backend accepts each job.",
    helper: "Diagnostic only. It consumes image try-on quota because accepted jobs keep running, but it isolates submit/Mongo/token latency.",
    method: "POST",
    path: "/api/v1/tryon submit only",
    isGeminiSafe: false,
    maxTotalRequests: 110,
    maxVirtualUsers: 110,
    estimatedTryOnCallsPerRequest: 1,
    estimatedSizingCallsPerRequest: 0,
  },
  {
    id: "tryon-no-image-real",
    label: "Try-on poll no image",
    description: "Submits a real SDK try-on and polls until completion without downloading the generated image payload.",
    helper: "Consumes one real image try-on per request. Use this to isolate Gemini/job timing from result image transfer.",
    method: "POST",
    path: "/api/v1/tryon -> /api/v1/tryon/status/:jobId?includeImage=false",
    isGeminiSafe: false,
    maxTotalRequests: 110,
    maxVirtualUsers: 110,
    estimatedTryOnCallsPerRequest: 1,
    estimatedSizingCallsPerRequest: 0,
  },
  {
    id: "tryon-real",
    label: "Real try-on job",
    description: "Submits a real SDK try-on job using Gemini 2.5 Flash Image override and waits for completion by status polling.",
    helper: "Consumes one real image try-on per request. Use small runs first.",
    method: "POST",
    path: "/api/v1/tryon -> /api/v1/tryon/status/:jobId",
    isGeminiSafe: false,
    maxTotalRequests: 110,
    maxVirtualUsers: 110,
    estimatedTryOnCallsPerRequest: 1,
    estimatedSizingCallsPerRequest: 0,
  },
  {
    id: "sdk-journey-no-image-real",
    label: "Full SDK journey polling no image",
    description: "Runs age-check, size result, try-on submit, and status polling without returning the generated image data.",
    helper: "Best stress diagnostic for real SDK path while avoiding huge base64 image transfer in polling responses.",
    method: "POST",
    path: "/api/v1/sizing/age-check -> /api/v1/sizing/recommend -> /api/v1/tryon -> /api/v1/tryon/status/:jobId?includeImage=false",
    isGeminiSafe: false,
    maxTotalRequests: 110,
    maxVirtualUsers: 110,
    estimatedTryOnCallsPerRequest: 1,
    estimatedSizingCallsPerRequest: 2,
  },
  {
    id: "sdk-journey-sse-real",
    label: "Exact SDK journey",
    description: "Runs the browser SDK behavior: sizing, try-on submit, SSE stream, plus 3s fallback status polling.",
    helper: "This mirrors shoppers today: /tryon/stream is primary, /status polling is backup, and generated images appear in samples.",
    method: "POST",
    path: "/api/v1/sizing/age-check -> /api/v1/sizing/recommend -> /api/v1/tryon -> /api/v1/tryon/stream + /status fallback",
    isGeminiSafe: false,
    maxTotalRequests: 110,
    maxVirtualUsers: 110,
    estimatedTryOnCallsPerRequest: 1,
    estimatedSizingCallsPerRequest: 2,
  },
  {
    id: "sdk-journey-job-stream-real",
    label: "Proposed SDK job-stream",
    description: "Runs copied test-lab SDK routes: sizing, try-on submit, a job-scoped SSE stream, then one result fetch when the job completes.",
    helper: "Experimental architecture in isolated /test-lab/sdk-mirror routes only. It does not call or change the real /api/v1 SDK try-on route.",
    method: "POST",
    path: "/api/test-lab/sdk-mirror/sizing/age-check -> /sizing/recommend -> /tryon -> /tryon/stream?jobId -> /tryon/result/:jobId",
    isGeminiSafe: false,
    maxTotalRequests: 110,
    maxVirtualUsers: 110,
    estimatedTryOnCallsPerRequest: 1,
    estimatedSizingCallsPerRequest: 2,
  },
  {
    id: "sdk-journey-real",
    label: "Full SDK journey polling image",
    description: "Runs the full shopper path with status polling that returns the generated image payload.",
    helper: "Fallback-path diagnostic. The real SDK uses SSE first, then polling only as backup.",
    method: "POST",
    path: "/api/v1/sizing/age-check -> /api/v1/sizing/recommend -> /api/v1/tryon -> /api/v1/tryon/status/:jobId",
    isGeminiSafe: false,
    maxTotalRequests: 110,
    maxVirtualUsers: 110,
    estimatedTryOnCallsPerRequest: 1,
    estimatedSizingCallsPerRequest: 2,
  },
];

export const CAPACITY_USER_PRESETS = [1, 5, 10, 25, 50, 100, 250, 500, 1000] as const;
export const CAPACITY_REQUEST_PRESETS = [10, 25, 50, 100, 150, 500, 1000, 2500, 5000, 10000] as const;

export const DEFAULT_CAPACITY_CONFIG = {
  targetId: "test",
  scenarioId: "health",
  totalRequests: 500,
  virtualUsers: 25,
  timeoutMs: 8000,
  tryOnModel: DEFAULT_CAPACITY_TRY_ON_MODEL,
  confirmLive: false,
  confirmGemini: false,
} as const;
