"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { getPdpStudioAsset, uploadPdpStudioAsset } from "../../platform/services/pdpStudioAssetService";
import { PdpStudioApiError } from "../../platform/services/pdpStudioApiClient";
import { createAnnotation, getApproval, getDesign, listAnnotations, listRevisions, renderDesignUrl, replyAnnotation, resolveAnnotation, restoreRevision, saveDesign, setApproval } from "../services/pdpStudioDesignService";
import { defaultEffects, type DesignAnnotation, type DesignApproval, type DesignDocument, type DesignLayer, type DesignRevision, type PdpDesign } from "../types/pdpStudioDesign";

type Tool = "select" | "draw" | "comment";
export function usePdpStudioEditor(designId: string) {
  const [design, setDesign] = useState<PdpDesign | null>(null); const [document, setDocument] = useState<DesignDocument | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null); const [tool, setTool] = useState<Tool>("select");
  const [past, setPast] = useState<DesignDocument[]>([]); const [future, setFuture] = useState<DesignDocument[]>([]);
  const [status, setStatus] = useState<"loading" | "saved" | "saving" | "error" | "conflict">("loading"); const [error, setError] = useState("");
  const [revisions, setRevisions] = useState<DesignRevision[]>([]); const [annotations, setAnnotations] = useState<DesignAnnotation[]>([]); const [approval, setApprovalState] = useState<DesignApproval | null>(null);
  const lastSaved = useRef(""); const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => { let live = true; void Promise.all([getDesign(designId), listRevisions(designId), listAnnotations(designId), getApproval(designId)]).then(async ([loaded, revs, notes, approvalValue]) => {
    const ids = [...new Set(loaded.document.layers.flatMap(layer => layer.assetId ? [layer.assetId] : []))]; const urls = new Map<string,string>();
    await Promise.all(ids.map(async id => { try { urls.set(id, (await getPdpStudioAsset(id)).url); } catch {} }));
    const hydrated = { ...loaded.document, layers: loaded.document.layers.map(layer => layer.assetId ? { ...layer, assetUrl: urls.get(layer.assetId) } : layer) };
    if (!live) return; setDesign(loaded); setDocument(hydrated); lastSaved.current = serialize(hydrated); setRevisions(revs); setAnnotations(notes); setApprovalState(approvalValue); setStatus("saved");
  }).catch(catchError); return () => { live = false; }; }, [designId]);
  const catchError = useCallback((reason: unknown) => { setError(reason instanceof Error ? reason.message : "The editor could not load this design."); setStatus(reason instanceof PdpStudioApiError && reason.status === 409 ? "conflict" : "error"); }, []);
  const persist = useCallback(async (checkpointName?: string) => { if (!design || !document || serialize(document) === lastSaved.current) return; setStatus("saving"); try { const clean = stripUrls(document); const saved = await saveDesign(design.id, { expectedRevision: design.revision, document: clean, ...(checkpointName ? { checkpointName } : {}) }); setDesign(saved); lastSaved.current = serialize(document); setStatus("saved"); setRevisions(await listRevisions(design.id)); } catch (reason) { catchError(reason); } }, [catchError, design, document]);
  useEffect(() => { if (!document || !design || serialize(document) === lastSaved.current || status === "loading" || status === "conflict") return; if (saveTimer.current) clearTimeout(saveTimer.current); saveTimer.current = setTimeout(() => void persist(), 750); return () => { if (saveTimer.current) clearTimeout(saveTimer.current); }; }, [design, document, persist, status]);
  const commit = useCallback((next: DesignDocument | ((current: DesignDocument) => DesignDocument)) => { setDocument(current => { if (!current) return current; const value = typeof next === "function" ? next(current) : next; setPast(items => [...items.slice(-49), current]); setFuture([]); return value; }); }, []);
  const updateLayer = useCallback((id: string, patch: Partial<DesignLayer>) => commit(current => ({ ...current, layers: current.layers.map(layer => layer.id === id ? { ...layer, ...patch } : layer) })), [commit]);
  const addLayer = useCallback((layer: DesignLayer) => { commit(current => ({ ...current, layers: [...current.layers, layer] })); setSelectedId(layer.id); }, [commit]);
  const addText = useCallback(() => addLayer({ id: crypto.randomUUID(), type: "text", name: "Text", text: "Double-click to edit", x: 100, y: 100, width: 520, height: 100, rotation: 0, opacity: 1, visible: true, locked: false, blendMode: "normal", fontFamily: "Inter", fontSize: 56, fontWeight: 600, color: "#111827", effects: defaultEffects() }), [addLayer]);
  const addShape = useCallback((shape: "rectangle" | "ellipse") => addLayer({ id: crypto.randomUUID(), type: "shape", name: shape === "ellipse" ? "Ellipse" : "Rectangle", shape, x: 160, y: 160, width: 320, height: 240, rotation: 0, opacity: 1, visible: true, locked: false, blendMode: "normal", fill: "#EEF3FF", stroke: "#315EF5", strokeWidth: 4, effects: defaultEffects() }), [addLayer]);
  const addDrawing = useCallback((points:number[]) => { if(points.length<4)return; const xs=points.filter((_,i)=>i%2===0), ys=points.filter((_,i)=>i%2===1), minX=Math.min(...xs), minY=Math.min(...ys), maxX=Math.max(...xs), maxY=Math.max(...ys); addLayer({id:crypto.randomUUID(),type:"drawing",name:"Drawing",x:minX,y:minY,width:Math.max(20,maxX-minX),height:Math.max(20,maxY-minY),rotation:0,opacity:1,visible:true,locked:false,blendMode:"normal",points:points.map((value,index)=>value-(index%2===0?minX:minY)),stroke:"#315EF5",strokeWidth:8,effects:defaultEffects()}); setTool("select") },[addLayer]);
  const insertImage = useCallback(async (file: File) => { if (!document) return; setStatus("saving"); try { const asset = await uploadPdpStudioAsset(file); const max = Math.min(document.canvas.width, document.canvas.height) * .55; const ratio = (asset.width ?? 1) / (asset.height ?? 1); const width = ratio >= 1 ? max : max * ratio; const height = ratio >= 1 ? max / ratio : max; addLayer({ id: crypto.randomUUID(), type: "image", name: file.name, assetId: asset.id, assetUrl: asset.url, x: (document.canvas.width-width)/2, y: (document.canvas.height-height)/2, width, height, rotation: 0, opacity: 1, visible: true, locked: false, blendMode: "normal", effects: defaultEffects() }); setStatus("saved"); } catch (reason) { catchError(reason); } }, [addLayer, catchError, document]);
  const removeSelected = useCallback(() => { if (!selectedId) return; commit(current => ({ ...current, layers: current.layers.filter(layer => layer.id !== selectedId) })); setSelectedId(null); }, [commit, selectedId]);
  const duplicateSelected = useCallback(() => { const layer = document?.layers.find(item => item.id === selectedId); if (!layer) return; addLayer({ ...layer, id: crypto.randomUUID(), name: `${layer.name} copy`, x: layer.x + 24, y: layer.y + 24 }); }, [addLayer, document, selectedId]);
  const moveLayer = useCallback((id: string, direction: -1 | 1) => commit(current => { const layers = [...current.layers], index = layers.findIndex(layer => layer.id === id), target = Math.max(0, Math.min(layers.length - 1, index + direction)); if (index < 0 || index === target) return current; const [layer] = layers.splice(index, 1); if (layer) layers.splice(target, 0, layer); return { ...current, layers }; }), [commit]);
  const undo = useCallback(() => { const previous = past[past.length-1]; if (!previous || !document) return; setPast(items => items.slice(0,-1)); setFuture(items => [document, ...items].slice(0,50)); setDocument(previous); }, [document,past]);
  const redo = useCallback(() => { const next = future[0]; if (!next || !document) return; setFuture(items => items.slice(1)); setPast(items => [...items, document].slice(-50)); setDocument(next); }, [document,future]);
  const restore = useCallback(async (revision: number) => { try { const restored = await restoreRevision(designId, revision); setDesign(restored); setDocument(restored.document); lastSaved.current = serialize(restored.document); setRevisions(await listRevisions(designId)); setStatus("saved"); } catch (reason) { catchError(reason); } }, [catchError, designId]);
  const addAnnotation = useCallback(async (x: number, y: number, body: string) => { const row = await createAnnotation(designId, { x, y, body }); setAnnotations(items => [...items, row]); return row; }, [designId]);
  const reply = useCallback(async (annotationId: string, body: string) => { const row = await replyAnnotation(designId, annotationId, body); setAnnotations(items => items.map(item => item.id === row.id ? row : item)); }, [designId]);
  const resolve = useCallback(async (annotationId: string, resolved: boolean) => { const row = await resolveAnnotation(designId, annotationId, resolved); setAnnotations(items => items.map(item => item.id === row.id ? row : item)); }, [designId]);
  const decide = useCallback(async (value: Pick<DesignApproval,"status"|"note">) => setApprovalState(await setApproval(designId, value)), [designId]);
  const selectedLayer = useMemo(() => document?.layers.find(layer => layer.id === selectedId) ?? null, [document, selectedId]);
  return { design, document, selectedId, selectedLayer, tool, status, error, revisions, annotations, approval, canUndo: past.length>0, canRedo: future.length>0, setTool, setSelectedId, setDocument: commit, updateLayer, addText, addShape, addDrawing, insertImage, removeSelected, duplicateSelected, moveLayer, undo, redo, save: () => persist("Manual save"), restore, addAnnotation, reply, resolve, decide, downloadUrl: renderDesignUrl(designId) };
}
function serialize(document: DesignDocument) { return JSON.stringify(stripUrls(document)); }
function stripUrls(document: DesignDocument): DesignDocument { return { ...document, layers: document.layers.map(({ assetUrl: _assetUrl, ...layer }) => layer) }; }
