"use client";
import Image from "next/image";
import { useRef, useState } from "react";
import type { useBrandKitUi } from "../../hooks/useBrandKitUi";
import { PdpStudioButton } from "../shared/PdpStudioButton";
type Ui=ReturnType<typeof useBrandKitUi>;
export function BrandAssetsPanel({ui}:{ui:Ui}){const logoRef=useRef<HTMLInputElement>(null),referenceRef=useRef<HTMLInputElement>(null),[color,setColor]=useState("#315EF5"),[font,setFont]=useState("");return <div className="grid gap-5">
 {ui.assetNotice?<p role="status" className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-700">{ui.assetNotice}</p>:null}
 <section className="grid gap-6 rounded-[var(--radius-pdp-xl)] border border-[var(--color-pdp-rule)] bg-white p-5 shadow-[var(--shadow-pdp-card)]">
  <AssetSection title="Logos" description="Private logo files injected into eligible generations."><Uploader inputRef={logoRef} onFile={file=>void ui.upload("logos",file)}/><AssetGrid assets={ui.brandInfo.logos}/></AssetSection>
  <AssetSection title="Reference images" description="Visual references for material, lighting and art direction."><Uploader inputRef={referenceRef} onFile={file=>void ui.upload("references",file)}/><AssetGrid assets={ui.brandInfo.references}/></AssetSection>
  <AssetSection title="Colors" description="Reusable brand palette."><div className="flex flex-wrap gap-2"><input type="color" value={color} onChange={e=>setColor(e.target.value)} className="h-10 w-14 rounded-lg border border-[#dfe3ea] p-1"/><PdpStudioButton variant="outline" onClick={()=>!ui.brandInfo.colors.includes(color)&&ui.setField("colors",[...ui.brandInfo.colors,color])}>Add color</PdpStudioButton>{ui.brandInfo.colors.map(value=><button key={value} onClick={()=>ui.setField("colors",ui.brandInfo.colors.filter(item=>item!==value))} title="Remove color" className="size-10 rounded-full border-2 border-white shadow ring-1 ring-[#dfe3ea]" style={{background:value}}/>)}</div></AssetSection>
  <AssetSection title="Fonts" description="Font families used by your brand."><div className="flex gap-2"><input value={font} onChange={e=>setFont(e.target.value)} placeholder="e.g. Inter" className="h-10 flex-1 rounded-xl border border-[#dfe3ea] px-3 text-sm"/><PdpStudioButton variant="outline" onClick={()=>{const value=font.trim();if(value&&!ui.brandInfo.fonts.includes(value))ui.setField("fonts",[...ui.brandInfo.fonts,value]);setFont("")}}>Add font</PdpStudioButton></div><div className="mt-3 flex flex-wrap gap-2">{ui.brandInfo.fonts.map(value=><button key={value} onClick={()=>ui.setField("fonts",ui.brandInfo.fonts.filter(item=>item!==value))} className="rounded-full bg-[#f3f4f6] px-3 py-1.5 text-xs text-[#334155]">{value} ×</button>)}</div></AssetSection>
  <div className="flex justify-end"><PdpStudioButton disabled={ui.saving} onClick={()=>void ui.save()}>{ui.saving?"Saving…":"Save Brand Kit"}</PdpStudioButton></div>
 </section></div>}
function AssetSection({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="border-b border-[#edf0f4] pb-6 last:border-0"><h2 className="text-base font-medium">{title}</h2><p className="mt-1 text-sm text-[var(--color-pdp-muted)]">{description}</p><div className="mt-4">{children}</div></section>}
function Uploader({inputRef,onFile}:{inputRef:React.RefObject<HTMLInputElement|null>;onFile(file:File):void}){return <><button onClick={()=>inputRef.current?.click()} className="grid min-h-24 w-full place-items-center rounded-xl border border-dashed border-[#cbd5e1] bg-[#f8fafc] text-sm text-[#64748b] hover:border-[#315EF5]">Drop an image here or browse files</button><input ref={inputRef} hidden type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)onFile(file);e.currentTarget.value=""}}/></>}
function AssetGrid({assets}:{assets:Ui["brandInfo"]["logos"]}){return assets.length?<div className="mt-3 grid grid-cols-3 gap-2 sm:grid-cols-5">{assets.map(asset=><div key={asset.id} className="relative aspect-square overflow-hidden rounded-xl border border-[#dfe3ea] bg-white"><Image src={asset.url} alt={asset.originalName??"Brand asset"} fill sizes="140px" className="object-contain p-2"/></div>)}</div>:null}
